name: "Weather Updater"
on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  update-weather:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Kill the Server
      - run: pkill -9 -f puma
      - name: Bundle Update
      - run: bundle install
      - name: Run Rails Server
      - run: rails s
